kind: Pod
apiVersion: v1
metadata:
  name: init-test 

spec:
  initContainers:
  - name: init-container
    image: busybox:latest
    command: ["sh" , "-c" , "echo 'Initialization started ...'; sleep 20 ; echo 'Initialization Completed ... ' "]

  containers:
  - name: main-container
    image: busybox:latest
    command: [ "sh" , "-c" , "echo 'Main container started ...' " ]
